apiVersion: v1
kind: Secret
metadata:
  name: django-env
  namespace: boleto
type: Opaque
stringData:
  DEBUG: "False"
  DJANGO_SECRET_KEY: "&8b4XF@Jc^6ZTL^UWu1yjLw40&Ssl3*C8T1o*tVUkdHWg^NpcI"
  ALLOWED_HOSTS: "*"    
  POSTGRES_DB: "boleto_db"
  POSTGRES_USER: "boleto_user"
  POSTGRES_PASSWORD: "Fe3dqsE&Ez^L"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"