apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
  namespace: boleto
spec:
  storageClassName: manual
  volumeName: staticfiles-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi