apiVersion: v1
kind: PersistentVolume
metadata:
    name: staticfiles-pv
    labels:
      type: local
      app: {{.Values.prefix}}-staticfiles
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.persistence.storage}}
  accessModes:
    - {{.Values.persistence.accessModes}}
  hostPath:
    path: {{.Values.persistence.mountPath}}