# Generated by Django 5.2.7 on 2025-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complemetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Komuna Baratza', max_length=200)),
                ('message', models.TextField(blank=True, default='Gracias por apoyar nuestra huerta comunitaria')),
                ('date', models.DateField(blank=True, help_text='Fecha del sorteo', null=True)),
                ('precio', models.CharField(blank=True, help_text='el precio del boleto', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Complentos',
                'verbose_name_plural': 'Complentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Texto que se muestra en el menú', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Orden en el menú (asc)')),
            ],
            options={
                'verbose_name': 'Elemento de menú',
                'verbose_name_plural': 'Elementos de menú',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Número del boleto', unique=True)),
                ('sorteo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-id'],
            },
        ),
    ]
