apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.app }}-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
        listen 80;

    location /static/ {
        #alias /app/static/;
        root /app;
        access_log off;
        expires 30d;
    }
        
        location / {
          proxy_pass http://{{ .Values.prefix }}-{{ .Values.app }}:{{ .Values.service.port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
    }