apiVersion: v2
name: postgres-chart
description: Helm chart wrapper para desplegar PostgreSQL usando Bitnami
type: application
version: 0.1.0
appVersion: "16"

dependencies:
  - name: postgresql
    version: 15.5.14
    repository: https://charts.bitnami.com/bitnami
